services:
    assetguard-base:
        build:
            context: ./assetguard-base
            args:
                ASSETGUARD_BRANCH: ${ASSETGUARD_BRANCH}
        pull_policy: never
        image: dev-assetguard-base
        networks:
            - assetguard-net

    certs-generator:
        build:
            context: ./certs-generator
        image: assetguard-certs-generator
        pull_policy: never
        volumes:
            - assetguard-certs:/certificates
            - ./config/assetguard_dashboard_certs:/export/dashboard
            - ./certs-generator/config.yml:/config/config.yml:ro
        restart: "no"
        networks:
            - assetguard-net

    assetguard.indexer:
        image: quay.io/wazuh/wazuh-indexer:5.0.0-0
        container_name: assetguard.indexer
        hostname: assetguard.indexer
        ports:
            - "9200:9200"
        networks:
            assetguard-net:
                aliases:
                    - assetguard.indexer
        volumes:
            - assetguard-indexer-data:/var/lib/assetguard-indexer
            - assetguard-certs:/etc/assetguard-indexer/certs
            - ./assetguard-indexer/assetguard.indexer.yml:/usr/share/assetguard-indexer/config/opensearch.yml:ro
        environment:
            - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
        depends_on:
            certs-generator:
                condition: service_completed_successfully
        healthcheck:
            test: ["CMD", "curl", "-k", "-u", "admin:admin", "https://localhost:9200/_cluster/health"]
            interval: 10s
            timeout: 5s
            retries: 20
            start_period: 120s

    assetguard.master:
        build:
            context: ./assetguard-manager
            target: server
        pull_policy: never
        image: dev-assetguard-manager
        hostname: assetguard.master
        networks:
            - assetguard-net
        ports:
            - "55050:55000"
        volumes:
            - assetguard-certs:/var/assetguard-manager/etc/certs
            - ${ASSETGUARD_LOCAL_PATH}/framework/scripts:/var/assetguard-manager/framework/scripts
            - ${ASSETGUARD_LOCAL_PATH}/api/scripts:/var/assetguard-manager/api/scripts
            - ${ASSETGUARD_LOCAL_PATH}/framework/assetguard:/var/assetguard-manager/framework/python/lib/python${ASSETGUARD_PYTHON_VERSION}/site-packages/assetguard
            - ${ASSETGUARD_LOCAL_PATH}/api/api:/var/assetguard-manager/framework/python/lib/python${ASSETGUARD_PYTHON_VERSION}/site-packages/api
        environment:
            OPENDISTRO_SECURITY_ENABLED: "false"
            NODE_NAME: "assetguard.master"
        entrypoint:
            - /scripts/entrypoint.sh
            - assetguard.master
            - master-node
            - master
        depends_on:
            assetguard.indexer:
                condition: service_healthy
            assetguard-base:
                condition: service_started

    assetguard.worker:
        image: dev-assetguard-manager
        hostname: assetguard.worker
        pull_policy: never
        networks:
            - assetguard-net
        volumes:
            - assetguard-certs:/var/assetguard-manager/etc/certs
            - ${ASSETGUARD_LOCAL_PATH}/framework/scripts:/var/assetguard-manager/framework/scripts
            - ${ASSETGUARD_LOCAL_PATH}/api/scripts:/var/assetguard-manager/api/scripts
            - ${ASSETGUARD_LOCAL_PATH}/framework/assetguard:/var/assetguard-manager/framework/python/lib/python${ASSETGUARD_PYTHON_VERSION}/site-packages/assetguard
            - ${ASSETGUARD_LOCAL_PATH}/api/api:/var/assetguard-manager/framework/python/lib/python${ASSETGUARD_PYTHON_VERSION}/site-packages/api
        depends_on:
            assetguard.master:
                condition: service_started
        environment:
            NODE_NAME: "assetguard.worker"
        ports:
            - "55051:55000"
        entrypoint:
            - /scripts/entrypoint.sh
            - assetguard.worker
            - worker

    assetguard2.worker:
        image: dev-assetguard-manager
        hostname: assetguard.worker
        pull_policy: never
        networks:
            - assetguard-net
        volumes:
            - assetguard-certs:/var/assetguard-manager/etc/certs
            - ${ASSETGUARD_LOCAL_PATH}/framework/scripts:/var/assetguard-manager/framework/scripts
            - ${ASSETGUARD_LOCAL_PATH}/api/scripts:/var/assetguard-manager/api/scripts
            - ${ASSETGUARD_LOCAL_PATH}/framework/assetguard:/var/assetguard-manager/framework/python/lib/python${ASSETGUARD_PYTHON_VERSION}/site-packages/assetguard
            - ${ASSETGUARD_LOCAL_PATH}/api/api:/var/assetguard-manager/framework/python/lib/python${ASSETGUARD_PYTHON_VERSION}/site-packages/api
        depends_on:
            assetguard.master:
                condition: service_started
        environment:
            NODE_NAME: "assetguard2.worker"
        ports:
            - "55052:55000"
        entrypoint:
            - /scripts/entrypoint.sh
            - assetguard2.worker
            - worker

    nginx-lb:
        build:
            context: ./nginx-lb
        image: dev-nginx-lb
        pull_policy: never
        restart: on-failure:5
        ports:
            - "1514:1514"
        networks:
            - assetguard-net
        depends_on:
            assetguard.master:
                condition: service_started
            assetguard.worker:
                condition: service_started
            assetguard2.worker:
                condition: service_started
        entrypoint:
            - /scripts/entrypoint.sh

    assetguard-agent:
        build:
            context: ./assetguard-agent
        image: dev-assetguard-agent
        pull_policy: never
        networks:
            - assetguard-net
        entrypoint:
            - /scripts/entrypoint.sh
            - nginx-lb
            - ${ASSETGUARD_VERSION}
        depends_on:
            nginx-lb:
                condition: service_started

    assetguard.dashboard:
        image: public.ecr.aws/wazuh-cicd/wazuh/wazuh-dashboard:5.0.0-latest
        container_name: assetguard.dashboard
        hostname: assetguard.dashboard
        networks:
            - assetguard-net
        ports:
            - "443:5601"
        volumes:
            - ./config/assetguard_dashboard_certs:/tmp/certs
            - ./assetguard-dashboard/assetguard.dashboard.yml:/usr/share/assetguard-dashboard/config/opensearch_dashboards.yml:ro
            - assetguard-dashboard-custom:/usr/share/assetguard-dashboard/plugins/assetguard/public/assets/custom
        depends_on:
            assetguard.indexer:
                condition: service_healthy

volumes:
  assetguard-indexer-data:
  assetguard-certs:
  assetguard-dashboard-custom:

networks:
  assetguard-net:
    driver: bridge
