nodes:
  indexer:
    - name: assetguard.indexer
      ip: assetguard.indexer

  server:
    - name: assetguard.master
      ip: assetguard.master
      node_type: master
    - name: assetguard.worker
      ip: assetguard.worker
      node_type: worker
    - name: assetguard2.worker
      ip: assetguard2.worker
      node_type: worker
  dashboard:
    - name: assetguard.dashboard
      ip: assetguard.dashboard
