name: dev-env-engine

services:
  assetguard-indexer:
    build:
      context: ./assetguard-indexer
    image: dev-assetguard-indexer
    pull_policy: build
    hostname: assetguard-indexer
    container_name: assetguard-indexer
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ./assetguard-indexer/entrypoint.sh:/entrypoint.sh:ro
      - ./certs:/certs:ro
      # Persistent data volume
      # - assetguard-indexer-data:/var/lib/assetguard-indexer
      # # Security initialization flag
      # - assetguard-indexer-config:/etc/assetguard-indexer-init
    ports:
      - 9200:9200

  assetguard-dashboard:
    build:
        context: ./assetguard-dashboard
    image: dev-assetguard-dashboard
    pull_policy: build
    hostname: assetguard-dashboard
    container_name: assetguard-dashboard
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ./assetguard-dashboard/entrypoint.sh:/entrypoint.sh:ro
      - ./certs:/certs:ro
    ports:
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - assetguard-indexer

# volumes:
#   assetguard-indexer-data:
#     driver: local
#   assetguard-indexer-config:
#     driver: local
