_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "$2y$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymrtI"
  reserved: true
  backend_roles:
  - "admin"
  description: "Admin user"

kibanaserver:
  hash: "$2y$12$91mPbiZ7fYo89SBbeeqGZeGj8ZeI3sUUDytxnylDZ3FV/.BX7qmHK"
  reserved: true
  backend_roles:
  - "kibanauser"
  description: "kibana server user"
