#include <gtest/gtest.h>

#include "hlp_test.hpp"

auto constexpr NAME = "quotedParser";
static const std::string TARGET = "/TargetField";

INSTANTIATE_TEST_SUITE_P(QuotedBuild,
                         HlpBuildTest,
                         ::testing::Values(BuildT(SUCCESS, getQuotedParser, {NAME, TARGET, {}, {}}),
                                           BuildT(SUCCESS, getQuotedParser, {NAME, TARGET, {}, {"q"}}),
                                           BuildT(SUCCESS, getQuotedParser, {NAME, TARGET, {}, {"q", "e"}}),
                                           BuildT(FAILURE, getQuotedParser, {NAME, TARGET, {}, {"quoted"}}),
                                           BuildT(FAILURE, getQuotedParser, {NAME, TARGET, {}, {"q", "escape"}}),
                                           BuildT(FAILURE, getQuotedParser, {NAME, TARGET, {}, {"q", "e", "?"}})));

INSTANTIATE_TEST_SUITE_P(QuotedParse,
                         HlpParseTest,
                         ::testing::Values(
                             // Default parameters
                             ParseT(FAILURE, "assetguard", {}, 0, getQuotedParser, {NAME, TARGET, {}, {}}),
                             ParseT(FAILURE, R"("assetguard 123)", {}, 0, getQuotedParser, {NAME, TARGET, {}, {}}),
                             ParseT(SUCCESS,
                                    R"("AssetGuard" 123)",
                                    j(fmt::format(R"({{"{}":"AssetGuard"}})", TARGET.substr(1))),
                                    7,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {}}),
                             ParseT(SUCCESS,
                                    R"("AssetGuard")",
                                    j(fmt::format(R"({{"{}":"AssetGuard"}})", TARGET.substr(1))),
                                    7,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {}}),
                             ParseT(SUCCESS,
                                    R"("hi my name is \"AssetGuard\"")",
                                    j(fmt::format(R"({{"{}":"hi my name is \"AssetGuard\""}})", TARGET.substr(1))),
                                    25,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {}}),
                             ParseT(SUCCESS,
                                    R"("hi my name is \"AssetGuard\"" 123456)",
                                    j(fmt::format(R"({{"{}":"hi my name is \"AssetGuard\""}})", TARGET.substr(1))),
                                    25,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {}}),
                             // Change " to '
                             ParseT(FAILURE, "assetguard'", {}, 0, getQuotedParser, {NAME, TARGET, {}, {"'"}}),
                             ParseT(FAILURE, R"('assetguard 123)", {}, 0, getQuotedParser, {NAME, TARGET, {}, {"'"}}),
                             ParseT(SUCCESS,
                                    R"('AssetGuard' 123)",
                                    j(fmt::format(R"({{"{}":"AssetGuard"}})", TARGET.substr(1))),
                                    7,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'"}}),
                             ParseT(SUCCESS,
                                    R"('AssetGuard')",
                                    j(fmt::format(R"({{"{}":"AssetGuard"}})", TARGET.substr(1))),
                                    7,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'"}}),
                             ParseT(SUCCESS,
                                    R"('hi my name is \'AssetGuard\'')",
                                    j(fmt::format(R"({{"{}":"hi my name is 'AssetGuard'"}})", TARGET.substr(1))),
                                    25,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'"}}),
                             ParseT(SUCCESS,
                                    R"('hi my name is \'AssetGuard\'' 123456)",
                                    j(fmt::format(R"({{"{}":"hi my name is 'AssetGuard'"}})", TARGET.substr(1))),
                                    25,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'"}}),
                             // Change " to ' and \ to :
                             ParseT(FAILURE, "assetguard'", {}, 0, getQuotedParser, {NAME, TARGET, {}, {"'", ":"}}),
                             ParseT(FAILURE, R"('assetguard 123)", {}, 0, getQuotedParser, {NAME, TARGET, {}, {"'", ":"}}),
                             ParseT(SUCCESS,
                                    R"('AssetGuard' 123)",
                                    j(fmt::format(R"({{"{}":"AssetGuard"}})", TARGET.substr(1))),
                                    7,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'", ":"}}),
                             ParseT(SUCCESS,
                                    R"('AssetGuard')",
                                    j(fmt::format(R"({{"{}":"AssetGuard"}})", TARGET.substr(1))),
                                    7,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'", ":"}}),
                             ParseT(SUCCESS,
                                    R"('hi my name is :'AssetGuard:'')",
                                    j(fmt::format(R"({{"{}":"hi my name is 'AssetGuard'"}})", TARGET.substr(1))),
                                    25,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'", ":"}}),
                             ParseT(SUCCESS,
                                    R"('hi my name is :'AssetGuard:'' 123456)",
                                    j(fmt::format(R"({{"{}":"hi my name is 'AssetGuard'"}})", TARGET.substr(1))),
                                    25,
                                    getQuotedParser,
                                    {NAME, TARGET, {}, {"'", ":"}})));

//         // TODO: We want to support this case ?
//         // Mantain " but change escape character to " (Like CSV files)
//         // TestCase {R"(assetguard")", false, {""}, Options {"\"", "\""}, fn(R"({})"), 0},
//         // TestCase {R"("assetguard 123)", false, {""}, Options {"\"", "\""}, fn(R"({})"), 10},
//         // TestCase {
//         //     R"("AssetGuard" 123)", true, {""}, Options {"\"", "\""}, fn(R"("AssetGuard")"), 7},
//         // TestCase {R"("AssetGuard")", true, {""}, Options {"\"", "\""}, fn(R"("AssetGuard")"), 7},
//         // TestCase {R"("hi my name is ""AssetGuard""")",
//         //           true,
//         //           {""},
//         //           Options {"\"", "\""},
//         //           fn(R"("hi my name is \"AssetGuard\"")"),
//         //           25},
//         // TestCase {R"("hi my name is ""AssetGuard"" 123456)",
//         //           true,
//         //           {""},
//         //           Options {"\"", "\""},
//         //           fn(R"("hi my name is \"AssetGuard\"")"),
//         //           25}
